import React, { useState, useEffect } from 'react';
import SectionHeader from '@/components/SectionHeader';
import { motion, AnimatePresence } from 'framer-motion';

interface Question {
  id: number;
  text: string;
  options: string[];
  correctAnswer: number;
}

interface Quiz {
  id: string;
  title: string;
  description: string;
  questions: Question[];
}

/**
 * QuizPage component - Main quiz interface
 * 
 * @component
 */
const QuizPage: React.FC = () => {
  const [quizzes, setQuizzes] = useState<Quiz[]>([
    {
      id: 'climate-basics',
      title: 'Climate Change Basics',
      description: 'Test your knowledge on fundamental climate science concepts',
      questions: [
        {
          id: 1,
          text: 'What is the primary greenhouse gas emitted by human activities?',
          options: ['Methane', 'Carbon Dioxide', 'Nitrous Oxide', 'Water Vapor'],
          correctAnswer: 1
        },
        {
          id: 2,
          text: 'Which sector contributes the most to global greenhouse gas emissions?',
          options: ['Transportation', 'Industry', 'Energy Production', 'Agriculture'],
          correctAnswer: 2
        }
      ]
    },
    {
      id: 'renewable-energy',
      title: 'Renewable Energy',
      description: 'Explore knowledge about clean energy technologies',
      questions: [
        {
          id: 1,
          text: 'Which renewable energy source has seen the fastest cost reduction in the past decade?',
          options: ['Wind Power', 'Solar Photovoltaic', 'Hydroelectric', 'Geothermal'],
          correctAnswer: 1
        },
        {
          id: 2,
          text: 'What percentage of global electricity was generated by renewables in 2022?',
          options: ['15%', '20%', '29%', '35%'],
          correctAnswer: 2
        }
      ]
    }
  ]);
  
  const [selectedQuiz, setSelectedQuiz] = useState<Quiz | null>(null);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [score, setScore] = useState(0);
  const [showResults, setShowResults] = useState(false);
  const [answeredQuestions, setAnsweredQuestions] = useState<boolean[]>([]);

  const handleQuizStart = (quiz: Quiz) => {
    setSelectedQuiz(quiz);
    setCurrentQuestionIndex(0);
    setSelectedOption(null);
    setScore(0);
    setShowResults(false);
    setAnsweredQuestions(new Array(quiz.questions.length).fill(false));
  };

  const handleOptionSelect = (optionIndex: number) => {
    if (selectedOption !== null || !selectedQuiz) return; // Prevent changing answer after selection
    
    setSelectedOption(optionIndex);
    
    // Update answered questions array
    const newAnswered = [...answeredQuestions];
    newAnswered[currentQuestionIndex] = true;
    setAnsweredQuestions(newAnswered);
    
    // Update score if correct
    if (optionIndex === selectedQuiz.questions[currentQuestionIndex].correctAnswer) {
      setScore(prev => prev + 1);
    }
  };

  const handleNextQuestion = () => {
    if (!selectedQuiz) return;
    
    if (currentQuestionIndex < selectedQuiz.questions.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
      setSelectedOption(null);
    } else {
      setShowResults(true);
    }
  };

  const resetQuiz = () => {
    setSelectedQuiz(null);
    setCurrentQuestionIndex(0);
    setSelectedOption(null);
    setScore(0);
    setShowResults(false);
    setAnsweredQuestions([]);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <SectionHeader 
        title="Quiz" 
        subtitle="Test your knowledge and learn more about climate topics" 
      />
      
      <div className="mt-8">
        {!selectedQuiz ? (
          // Quiz Selection View
          <div className="max-w-4xl mx-auto">
            <h2 className="text-2xl font-semibold text-slate-800 mb-6">Available Quizzes</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {quizzes.map((quiz, index) => (
                <motion.div
                  key={quiz.id}
                  className="bg-white rounded-xl shadow-lg p-6 border border-slate-200 cursor-pointer hover:shadow-xl transition-shadow"
                  whileHover={{ y: -5 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={() => handleQuizStart(quiz)}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                >
                  <h3 className="text-xl font-bold text-emerald-600 mb-2">{quiz.title}</h3>
                  <p className="text-slate-600 mb-4">{quiz.description}</p>
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-slate-500">{quiz.questions.length} questions</span>
                    <button className="px-4 py-2 bg-emerald-500 text-white rounded-lg hover:bg-emerald-600 transition-colors">
                      Start Quiz
                    </button>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        ) : showResults ? (
          // Results View
          <div className="max-w-3xl mx-auto">
            <motion.div 
              className="bg-white rounded-xl shadow-lg p-8 text-center"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
            >
              <h2 className="text-3xl font-bold text-emerald-600 mb-4">Quiz Completed!</h2>
              <p className="text-5xl font-bold text-slate-800 mb-2">{score}/{selectedQuiz.questions.length}</p>
              <p className="text-xl text-slate-600 mb-8">Correct Answers</p>
              
              <div className="mb-8">
                <div className="w-full bg-gray-200 rounded-full h-4 mb-2">
                  <div 
                    className="bg-emerald-500 h-4 rounded-full transition-all duration-1000 ease-out"
                    style={{ width: `${(score / selectedQuiz.questions.length) * 100}%` }}
                  ></div>
                </div>
                <p className="text-slate-600">{Math.round((score / selectedQuiz.questions.length) * 100)}% Correct</p>
              </div>
              
              <div className="flex justify-center gap-4">
                <button 
                  onClick={resetQuiz}
                  className="px-6 py-3 bg-slate-200 text-slate-800 rounded-lg hover:bg-slate-300 transition-colors"
                >
                  Try Another Quiz
                </button>
                <button 
                  onClick={() => {
                    setSelectedQuiz(null);
                    resetQuiz();
                  }}
                  className="px-6 py-3 bg-emerald-500 text-white rounded-lg hover:bg-emerald-600 transition-colors"
                >
                  Back to Quizzes
                </button>
              </div>
            </motion.div>
          </div>
        ) : (
          // Quiz Taking View
          <div className="max-w-3xl mx-auto">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-2xl font-semibold text-slate-800">{selectedQuiz.title}</h2>
              <span className="text-lg text-slate-600">
                Question {currentQuestionIndex + 1} of {selectedQuiz.questions.length}
              </span>
            </div>
            
            <motion.div 
              className="bg-white rounded-xl shadow-lg p-6 mb-6"
              key={currentQuestionIndex}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
            >
              <h3 className="text-xl font-semibold text-slate-800 mb-6">
                {selectedQuiz.questions[currentQuestionIndex].text}
              </h3>
              
              <div className="space-y-3">
                {selectedQuiz.questions[currentQuestionIndex].options.map((option, index) => (
                  <motion.button
                    key={index}
                    className={`w-full text-left p-4 rounded-lg border transition-colors ${
                      selectedOption === index 
                        ? index === selectedQuiz.questions[currentQuestionIndex].correctAnswer
                          ? 'border-emerald-500 bg-emerald-50'
                          : 'border-red-500 bg-red-50'
                        : 'border-slate-200 hover:bg-slate-50'
                    }`}
                    onClick={() => handleOptionSelect(index)}
                    disabled={selectedOption !== null}
                    whileHover={{ scale: selectedOption === null ? 1.02 : 1 }}
                    whileTap={{ scale: 0.98 }}
                  >
                    <div className="flex items-center">
                      <span className="mr-3 font-medium">{String.fromCharCode(65 + index)}.</span>
                      <span>{option}</span>
                      {selectedOption === index && index === selectedQuiz.questions[currentQuestionIndex].correctAnswer && (
                        <span className="ml-auto text-emerald-500 font-semibold">✓ Correct!</span>
                      )}
                      {selectedOption === index && index !== selectedQuiz.questions[currentQuestionIndex].correctAnswer && (
                        <span className="ml-auto text-red-500 font-semibold">✗ Incorrect</span>
                      )}
                    </div>
                  </motion.button>
                ))}
              </div>
            </motion.div>
            
            <div className="flex justify-between">
              <button 
                onClick={resetQuiz}
                className="px-6 py-3 bg-slate-200 text-slate-800 rounded-lg hover:bg-slate-300 transition-colors"
              >
                Back to Quizzes
              </button>
              
              <button 
                onClick={handleNextQuestion}
                disabled={selectedOption === null}
                className={`px-6 py-3 rounded-lg transition-colors ${
                  selectedOption !== null 
                    ? 'bg-emerald-500 text-white hover:bg-emerald-600' 
                    : 'bg-slate-200 text-slate-400 cursor-not-allowed'
                }`}
              >
                {currentQuestionIndex < selectedQuiz.questions.length - 1 ? 'Next Question' : 'Finish Quiz'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default QuizPage;